name: juicy-tf
on:
  pull_request:
jobs:
  check_terraform_fmt:
    name: Check Terraform Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ${{ github.workspace }}/scripts/check-terraform-formatting.sh
